### ISSUE TITLE
Error compiling fragment shader

### ISSUE THREAD

**Issue by zmertens** [ArturKovacs/GL-raytracer#1] opened 2018-01-05 07:44 UTC
https://github.com/ArturKovacs/GL-raytracer/blob/ebd2a552a07d62c1045cfdb56d57496122dcea37/fragment.glsl#L240

Just needed to change the `-1` value to `-1.0f` to get it to compile

**Comment by ArturKovacs** [comment] 2018-01-05 09:21
Hello there!

First of all thank you kind Sir for taking the time to open an issue on this abandoned, shamefully old repository of mine.

I cloned the repo quickly, and I did in fact get an error on that line and after applying your proposed solution, the shaders compile. However I don't get any image produced by the shader all I see in the window is something that seems weird framebuffer remains. I haven't started digging in but I'm sure this is caused by a bug in the main.cpp.

Did you have to change anything in the main.cpp to make it work and if so what was it? Which GPU driver are you using? I'm using the open source AMD driver, "radeon".

**Comment by zmertens** [comment] 2018-01-05 09:43
I got it working on a different computer `Nvidia GTX 970 gpu`, but the computer that had the compilation error was using an Intel CPU with onboard graphics. I got it to compile but got the black screen as well. I can post more info later on.

Thanks for the quick response.

**Comment by ArturKovacs** [comment] 2018-01-06 17:51
Unfortunately I can't allocate time to work on this in the near future, but if you make a pull request, I will be happy to merge a fix.

**Comment by ArturKovacs** [comment] 2018-10-24 21:12
Fixed by #2.

**Closed as completed** 2018-10-24 21:11 UTC
